### PR TITLE
Fix/cors error

### LINKED ISSUE #674: [Story] Chec-cors error

### PR DESCRIPTION
**Pull request by aliassan**
# Description

Debug CORS error.

Fixes #674 

## Contribution

For your PR please add a comment to each file edited to explain the changes you made.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

- **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Checklist

- /app

```bash
npm run build
npm run test:unit
npm run type-check
npm run lint
npm run format
```

- /backend

```bash
npm run build
npm run test
npm run lint
npm run format
```

- /contract

```bash
npm run test
npm run lint
npm run format
```

### CODE REVIEW

**Review by dasarathg68 — COMMENTED** [review]
Can you point the reason for the cors error?
Is it due to the rate limiter?

**Comment by dasarathg68** [comment]
> > Can you point the reason for the cors error? Is it due to the rate limiter?
> 
> Yes, it looks looks like it's the rate limiter. You can try running this branch on your side to confirm. You'll probably get a similar error from ConGecko API for it's rate limiter if you switch around the different pages quickly.

Ah okay! It's working for me. No errors so far.

**Review by dasarathg68 — APPROVED** [review]
LGTM

File: backend/src/config/serverConfig.ts
Comment (hermannleboss) [inline backend/src/config/serverConfig.ts:1]: I think for this we just need to increase the limit. 
Now the think is we are exposed to DDOS without it. 
And if this is a problem, that mean we have a problem with the fact that the frontend is not optimized and is making too much request to the backend.

File: backend/src/config/serverConfig.ts [hunk 1]
```diff
@@ -53,12 +53,12 @@ class Server {
...
       apidocs: "/api-docs",
     };
-    const limiter = rateLimit({
-      windowMs: 15 * 60 * 1000, // 15 minutes
-      max: 100, // max 100 requests per windowMs
-    });
+    // const limiter = rateLimit({
+    //   windowMs: 15 * 60 * 1000, // 15 minutes
+    //   max: 100, // max 100 requests per windowMs
+    // });
```
Comment (hermannleboss) [inline backend/src/config/serverConfig.ts:59]:
```suggestion
    const limiter = rateLimit({
      windowMs: 15 * 60 * 1000, // 15 minutes
      max: 1000, // max 1000 requests per windowMs
    });
```

File: backend/src/config/serverConfig.ts [hunk 2]
```diff
@@ -53,12 +53,12 @@ class Server {
...
 
-    this.app.use(limiter);
+    // this.app.use(limiter);
```
Comment (hermannleboss) [inline backend/src/config/serverConfig.ts:61]:
```suggestion
    this.app.use(limiter);
```

**Review by hermannleboss — APPROVED** [review]
LGTM
