### PR TITLE
fix: redirect user after token expiry

### LINKED ISSUE #55: issue: No redirection when the token is not valid again
When the token validation date has passed, normaly it should redirect to login page, but don't.
image

You can't navigate.

### PR DESCRIPTION
**Pull request by dasarathg68**
# Description

Clears the token, logs the user out from the application and redirects it to /login by calling the logout method.

Fixes #55 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines

### CODE REVIEW

File: app/src/apis/authApi.ts [hunk 1]
```diff
@@ -19,6 +19,7 @@ export class AuthAPI {
       return true
     } else {
       //return false
```
Comment (farrellh1) [inline app/src/apis/authApi.ts:21]: i think the name of the function is typo, it should be `verifyToken` right?

Comment (dasarathg68) [reply app/src/apis/authApi.ts:21]: Yes, let me change that. 
Any other suggestions?

**Review by farrellh1 — APPROVED** [review]
LGTM 🚀
