### PR TITLE
Bugfix/ Image expire in the CNC

### LINKED ISSUE #1634: [Bug] Image expire in the CNC, you upload images or asset the expire, solve the problem
## Description

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Georginio-prod**
# Description

## Intial Issue Description

In this project, I did a refactoring in the image storage management.
.
Fixes #1634 

## Issues introduced and fixed (Optional)

If exit: The description of issues you find and fix in this PR.

## PR Summary Or Solution description

The summary should be a short description of the change, what you have done to fixe the issue. Please include the motivation for the change and how it was implemented. If applicable, please include screenshots or code snippets to illustrate the changes.

## Contribution

For your PR please add a comment to each file edited to explain the changes you made.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

- **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Contribution checklist

Before submitting the PR, please make sure you have applied the rules in [CONTRIBUTION.md](./../CONTRIBUTION.md)

### CODE REVIEW

File: backend/src/controllers/authController.ts [hunk 1]
```diff
@@ -1,10 +1,27 @@
...
+  }
+  return 'faker';
+};
+
+const generateFakerAvatar = (address: string): string => {
+  const seed = Array.from(address).reduce((sum, char) => sum + char.charCodeAt(0), 0);
+  faker.seed(seed);
+  return faker.image.avatar();
+};
+
```
Comment (hermannleboss) [inline backend/src/controllers/authController.ts]: C'est des fonctions qui meritent d'etre dans utils

**Review by hermannleboss — CHANGES_REQUESTED** [review]
LGTM, just update to use the utils
ANd your PR dont have a linked issue

**Review by hermannleboss — APPROVED** [review]
lgtm
