### PR TITLE
[BUG] Fix dividend transaction history

### LINKED ISSUE #1276: [BUG] Fix dividend transaction history
## Description

**Describe the bug**
The transaction history for dividend is not working since we update the pay dividend feature

### PR DESCRIPTION
**Pull request by achillegley**
# Description

## Intial Issue Description
The transaction history for dividend is not working since we update the pay dividend feature

> Link to the issue in the kanban board
> If no issue exists, please create one and link it here.
Fixes #1276 

## Issues introduced and fixed (Optional)

If exit: The description of issues you find and fix in this PR.

## PR Summary Or Solution description

update the graph to logs dividendClaim and TokenDividend Claime event from the bank contract. 
request the logs and display them in SherTokenView. 

image

fund bank message is now being displayed according to the selected token.  and the submit button is disabled if we need to fund the bank. 
image

image

 
## Contribution

For your PR please add a comment to each file edited to explain the changes you made.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

- **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Contribution checklist

Before submitting the PR, please make sure you have applied the rules in [CONTRIBUTION.md](./../CONTRIBUTION.md)

### CODE REVIEW

File: app/src/views/team/[id]/BankView.vue
Comment (achillegley) [inline app/src/views/team/[id]/BankView.vue]: remove holding dividens from bankSection

File: app/src/components/sections/SherTokenView/DividendsBalancesSection.vue [hunk 1]
```diff
@@ -40,16 +40,15 @@ import type { Address } from 'viem'
...
 
-interface Props {
-  address: Address
-}
-const props = defineProps<Props>()
-
-const { dividends, isLoading } = useContractBalance(props.address)
+const { dividends, isLoading } = useContractBalance(
+  teamStore.getContractAddressByType('Bank') as Address
+)
```
Comment (hermannleboss) [inline app/src/components/sections/SherTokenView/DividendsBalancesSection.vue]: If you have to ass Address that mean there is a problem. 


getContractAddressByType return Address | Undefine

So useContractBalance should be able to recieve the same thing, and do the opperation only when the address is not undefine.

**Review by hermannleboss — APPROVED** [review]
LGTM
